data:
  name: Mvtec_examples
  group1: "good bottle from top view"
  group2: "broken bottle from top view with large crack"

# proposer:  # LLM Proposer
#   num_samples: 2  # number of samples per group to use
